export const sellers = [
  {
    userId: 2,
    shopName: "Fashion Paradise",
    shopLogo: "https://images.unsplash.com/photo-1445205170230-053b83016050?ixlib=rb-4.0.3",
    description: "Cửa hàng thời trang cao cấp, cung cấp những mẫu quần áo mới nhất theo xu hướng.",
    rating: 4.8,
    reviewCount: 1250,
    productCount: 24,
    shopType: "official",
    isVerified: true,
    address: "123 Nguyễn Trãi, Quận 1, TP.HCM",
    phone: "0901234567",
    email: "fashionparadise@gmail.com",
    mainCategory: "Áo thun",
    bannerImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3"
  },
  {
    userId: 3,
    shopName: "Trendy Store",
    shopLogo: "https://images.unsplash.com/photo-1589363360147-4f2d51541551?ixlib=rb-4.0.3",
    description: "Shop thời trang trẻ trung dành cho giới trẻ, luôn cập nhật xu hướng mới nhất.",
    rating: 4.6,
    reviewCount: 980,
    productCount: 18,
    shopType: "preferred",
    isVerified: true,
    address: "45 Lê Lợi, Quận 1, TP.HCM",
    phone: "0912345678",
    email: "trendystore@gmail.com",
    mainCategory: "Áo sơ mi",
    bannerImage: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?ixlib=rb-4.0.3"
  },
  {
    userId: 4,
    shopName: "Elegance Boutique",
    shopLogo: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-4.0.3",
    description: "Cửa hàng thời trang thanh lịch cao cấp dành cho phụ nữ hiện đại.",
    rating: 4.9,
    reviewCount: 1530,
    productCount: 22,
    shopType: "official",
    isVerified: true,
    address: "78 Đồng Khởi, Quận 1, TP.HCM",
    phone: "0923456789",
    email: "eleganceboutique@gmail.com",
    mainCategory: "Váy đầm",
    bannerImage: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?ixlib=rb-4.0.3"
  },
  {
    userId: 5,
    shopName: "Urban Style",
    shopLogo: "https://images.unsplash.com/photo-1507680434567-5739c80be1ac?ixlib=rb-4.0.3",
    description: "Thời trang đường phố sành điệu, phong cách hiện đại cho cả nam và nữ.",
    rating: 4.7,
    reviewCount: 1150,
    productCount: 20,
    shopType: "preferred",
    isVerified: true,
    address: "25 Huỳnh Thúc Kháng, Quận 1, TP.HCM",
    phone: "0934567890",
    email: "urbanstyle@gmail.com",
    mainCategory: "Quần jean",
    bannerImage: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?ixlib=rb-4.0.3"
  },
  {
    userId: 6,
    shopName: "Luxe Fashion",
    shopLogo: "https://images.unsplash.com/photo-1537832816519-689ad163238b?ixlib=rb-4.0.3",
    description: "Cửa hàng thời trang cao cấp với các thiết kế độc quyền, sang trọng.",
    rating: 4.9,
    reviewCount: 860,
    productCount: 16,
    shopType: "official",
    isVerified: true,
    address: "100 Nguyễn Huệ, Quận 1, TP.HCM",
    phone: "0945678901",
    email: "luxefashion@gmail.com",
    mainCategory: "Váy đầm",
    bannerImage: "https://images.unsplash.com/photo-1555529771-122e5d9f2341?ixlib=rb-4.0.3"
  },
  {
    userId: 7,
    shopName: "Vintage Collection",
    shopLogo: "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?ixlib=rb-4.0.3",
    description: "Shop thời trang vintage, tái hiện phong cách cổ điển với cách điệu hiện đại.",
    rating: 4.5,
    reviewCount: 720,
    productCount: 14,
    shopType: "normal",
    isVerified: true,
    address: "56 Trần Hưng Đạo, Quận 1, TP.HCM",
    phone: "0956789012",
    email: "vintagecollection@gmail.com",
    mainCategory: "Áo sơ mi",
    bannerImage: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?ixlib=rb-4.0.3"
  },
  {
    userId: 8,
    shopName: "Minimalist Store",
    shopLogo: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-4.0.3",
    description: "Thời trang tối giản, đơn giản nhưng tinh tế, phù hợp với phong cách hiện đại.",
    rating: 4.7,
    reviewCount: 890,
    productCount: 17,
    shopType: "preferred",
    isVerified: true,
    address: "32 Lý Tự Trọng, Quận 1, TP.HCM",
    phone: "0967890123",
    email: "minimaliststore@gmail.com",
    mainCategory: "Áo thun",
    bannerImage: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?ixlib=rb-4.0.3"
  },
  {
    userId: 9,
    shopName: "Sporty Life",
    shopLogo: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-4.0.3",
    description: "Cửa hàng thời trang thể thao, năng động, phù hợp cho người yêu thể thao và cuộc sống năng động.",
    rating: 4.6,
    reviewCount: 750,
    productCount: 15,
    shopType: "normal",
    isVerified: true,
    address: "15 Nguyễn Du, Quận 1, TP.HCM",
    phone: "0978901234",
    email: "sportylife@gmail.com",
    mainCategory: "Thể thao",
    bannerImage: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?ixlib=rb-4.0.3"
  },
  {
    userId: 10,
    shopName: "Eco Clothes",
    shopLogo: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?ixlib=rb-4.0.3",
    description: "Thời trang thân thiện với môi trường, sử dụng vật liệu tái chế và hữu cơ.",
    rating: 4.8,
    reviewCount: 650,
    productCount: 13,
    shopType: "preferred",
    isVerified: true,
    address: "89 Hai Bà Trưng, Quận 1, TP.HCM",
    phone: "0989012345",
    email: "ecoclothes@gmail.com",
    mainCategory: "Áo thun",
    bannerImage: "https://images.unsplash.com/photo-1511556820780-d912e42b4980?ixlib=rb-4.0.3"
  },
  {
    userId: 11,
    shopName: "Kids Fashion",
    shopLogo: "https://images.unsplash.com/photo-1626609636042-46da2103153c?ixlib=rb-4.0.3",
    description: "Cửa hàng thời trang dành cho trẻ em, đa dạng sản phẩm từ sơ sinh đến teenager.",
    rating: 4.9,
    reviewCount: 920,
    productCount: 19,
    shopType: "official",
    isVerified: true,
    address: "44 Lê Thánh Tôn, Quận 1, TP.HCM",
    phone: "0990123456",
    email: "kidsfashion@gmail.com",
    mainCategory: "Thời trang trẻ em",
    bannerImage: "https://images.unsplash.com/photo-1626784215021-2faa68a1a4c5?ixlib=rb-4.0.3"
  }
];

export const categories = [
  {
    name: "Áo thun",
    slug: "ao-thun",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-4.0.3"
  },
  {
    name: "Áo sơ mi",
    slug: "ao-so-mi",
    image: "https://images.unsplash.com/photo-1598961942613-ba897716405b?ixlib=rb-4.0.3"
  },
  {
    name: "Quần jean",
    slug: "quan-jean",
    image: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?ixlib=rb-4.0.3"
  },
  {
    name: "Váy đầm",
    slug: "vay-dam",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?ixlib=rb-4.0.3"
  },
  {
    name: "Giày",
    slug: "giay",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?ixlib=rb-4.0.3"
  },
  {
    name: "Phụ kiện",
    slug: "phu-kien",
    image: "https://images.unsplash.com/photo-1583292650898-7298fa6cf312?ixlib=rb-4.0.3"
  },
  {
    name: "Thời trang trẻ em",
    slug: "thoi-trang-tre-em",
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?ixlib=rb-4.0.3"
  },
  {
    name: "Thể thao",
    slug: "the-thao",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3"
  }
];

// Import script cập nhật sellerId
// Tạo dữ liệu sản phẩm
const productsData = [
  // Áo thun (10 sản phẩm)
  {
    name: "Áo thun basic nam cổ tròn",
    description: "Áo thun nam chất liệu cotton 100%, kiểu dáng basic, dễ phối đồ.",
    price: 189000,
    discountPrice: 129000,
    category: "Áo thun",
    subcategory: "Áo thun nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xám", "Xanh navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: 100,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 30
  },
  {
    name: "Áo thun nữ form rộng",
    description: "Áo thun nữ form rộng phong cách Hàn Quốc, chất vải mềm mại thoáng mát.",
    price: 159000,
    discountPrice: 99000,
    category: "Áo thun",
    subcategory: "Áo thun nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1618354691438-25bc04584c23?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Hồng", "Xanh mint", "Vàng nhạt"],
    sizes: ["S", "M", "L"],
    stock: 80,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 35
  },
  {
    name: "Áo thun nam in họa tiết",
    description: "Áo thun nam in họa tiết thời trang, chất liệu cotton cao cấp.",
    price: 220000,
    discountPrice: 165000,
    category: "Áo thun",
    subcategory: "Áo thun nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xanh dương"],
    sizes: ["M", "L", "XL"],
    stock: 60,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo thun oversize unisex",
    description: "Áo thun oversize unisex form rộng thụng phong cách Hàn Quốc.",
    price: 199000,
    discountPrice: 149000,
    category: "Áo thun",
    subcategory: "Áo thun unisex",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xám"],
    sizes: ["M", "L", "XL"],
    stock: 75,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Áo thun nữ crop top",
    description: "Áo thun nữ crop top kiểu dáng năng động trẻ trung.",
    price: 169000,
    discountPrice: 119000,
    category: "Áo thun",
    subcategory: "Áo thun nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1566428361931-7cf6b0f4a8ae?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Hồng", "Xanh nhạt"],
    sizes: ["S", "M", "L"],
    stock: 70,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 30
  },
  {
    name: "Áo thun nam cổ trụ",
    description: "Áo thun nam cổ trụ chất liệu cotton cao cấp, kiểu dáng lịch sự.",
    price: 229000,
    discountPrice: 179000,
    category: "Áo thun",
    subcategory: "Áo thun nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1579888944880-d98341245702?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xanh navy", "Đỏ đô"],
    sizes: ["M", "L", "XL", "XXL"],
    stock: 50,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo thun in logo thương hiệu",
    description: "Áo thun unisex in logo thương hiệu, phong cách thể thao năng động.",
    price: 259000,
    discountPrice: 199000,
    category: "Áo thun",
    subcategory: "Áo thun unisex",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1613852348851-df1739db8201?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xanh dương", "Đỏ"],
    sizes: ["S", "M", "L", "XL"],
    stock: 90,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo thun nữ kẻ sọc",
    description: "Áo thun nữ kẻ sọc, phong cách thanh lịch trẻ trung.",
    price: 179000,
    discountPrice: 129000,
    category: "Áo thun",
    subcategory: "Áo thun nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?ixlib=rb-4.0.3"],
    colors: ["Trắng kẻ đen", "Trắng kẻ xanh", "Trắng kẻ đỏ"],
    sizes: ["S", "M", "L"],
    stock: 45,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Áo thun nam dài tay",
    description: "Áo thun nam dài tay chất liệu cotton co giãn, phù hợp cho mùa thu đông.",
    price: 239000,
    discountPrice: 189000,
    category: "Áo thun",
    subcategory: "Áo thun nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xám", "Xanh navy"],
    sizes: ["M", "L", "XL", "XXL"],
    stock: 60,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo thun nữ tay lỡ phối màu",
    description: "Áo thun nữ tay lỡ phối màu trẻ trung, năng động.",
    price: 199000,
    discountPrice: 149000,
    category: "Áo thun",
    subcategory: "Áo thun nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1618354691321-e851c8d32856?ixlib=rb-4.0.3"],
    colors: ["Trắng phối xanh", "Trắng phối đen", "Trắng phối đỏ"],
    sizes: ["S", "M", "L"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },

  // Áo sơ mi (10 sản phẩm)
  {
    name: "Áo sơ mi nam dài tay trắng công sở",
    description: "Áo sơ mi nam trắng chất liệu cotton cao cấp, kiểu dáng công sở.",
    price: 329000,
    discountPrice: 259000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?ixlib=rb-4.0.3"],
    colors: ["Trắng"],
    sizes: ["M", "L", "XL", "XXL"],
    stock: 80,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo sơ mi nữ công sở cơ bản",
    description: "Áo sơ mi nữ công sở form cơ bản, chất liệu mềm mại.",
    price: 289000,
    discountPrice: 229000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1559807015-e5fe4e5484d9?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Xanh nhạt", "Hồng nhạt"],
    sizes: ["S", "M", "L", "XL"],
    stock: 70,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Áo sơ mi nam kẻ caro",
    description: "Áo sơ mi nam họa tiết kẻ caro, phong cách trẻ trung, dễ phối đồ.",
    price: 299000,
    discountPrice: 229000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1586363104826-3e17b0e0de97?ixlib=rb-4.0.3"],
    colors: ["Đỏ caro", "Xanh caro", "Vàng caro"],
    sizes: ["M", "L", "XL"],
    stock: 60,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Áo sơ mi nữ tay dài cổ bẻ",
    description: "Áo sơ mi nữ tay dài cổ bẻ, kiểu dáng thanh lịch, phù hợp đi làm, đi chơi.",
    price: 269000,
    discountPrice: 199000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1604954055072-634e95b3edd3?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Xanh nhạt", "Hồng nhạt", "Đen"],
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Áo sơ mi nam ngắn tay",
    description: "Áo sơ mi nam ngắn tay chất liệu thoáng mát, thích hợp cho mùa hè.",
    price: 269000,
    discountPrice: 219000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1611937661531-71ddd531623a?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Xanh nhạt", "Kem", "Xám nhạt"],
    sizes: ["M", "L", "XL", "XXL"],
    stock: 60,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo sơ mi nữ thêu hoa",
    description: "Áo sơ mi nữ màu trắng thêu hoa tinh tế, phong cách nữ tính.",
    price: 329000,
    discountPrice: 279000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1516483638261-f4dbaf036963?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Xanh nhạt"],
    sizes: ["S", "M", "L"],
    stock: 40,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo sơ mi nam denim",
    description: "Áo sơ mi nam chất liệu denim, phong cách bụi bặm, thích hợp đi chơi.",
    price: 359000,
    discountPrice: 289000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1513311068348-19c8fbdc0bb6?ixlib=rb-4.0.3"],
    colors: ["Xanh đậm", "Xanh nhạt"],
    sizes: ["M", "L", "XL"],
    stock: 50,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Áo sơ mi nữ cổ đức",
    description: "Áo sơ mi nữ cổ đức kiểu dáng trẻ trung, thanh lịch, dễ phối đồ.",
    price: 289000,
    discountPrice: 239000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1518021929237-cf0c61bb7449?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Xanh nhạt", "Hồng phấn", "Đen"],
    sizes: ["S", "M", "L", "XL"],
    stock: 60,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 15
  },
  {
    name: "Áo sơ mi nam linen",
    description: "Áo sơ mi nam chất liệu linen mát mẻ, thích hợp cho mùa hè.",
    price: 399000,
    discountPrice: 329000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1607389915878-b8b90792d95c?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Kem", "Be", "Xám nhạt"],
    sizes: ["M", "L", "XL", "XXL"],
    stock: 40,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Áo sơ mi nữ voan",
    description: "Áo sơ mi nữ chất liệu voan mỏng nhẹ, kiểu dáng nữ tính.",
    price: 299000,
    discountPrice: 249000,
    category: "Áo sơ mi",
    subcategory: "Áo sơ mi nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1623227713632-29c71141465a?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Hồng nhạt", "Xanh mint"],
    sizes: ["S", "M", "L"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 15
  },

  // Quần jean (10 sản phẩm)
  {
    name: "Quần jean nam skinny",
    description: "Quần jean nam skinny ôm dáng, màu xanh đậm, thích hợp mọi dáng người.",
    price: 459000,
    discountPrice: 359000,
    category: "Quần jean",
    subcategory: "Quần jean nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1582418702059-97ebafb35d09?ixlib=rb-4.0.3"],
    colors: ["Xanh đậm", "Xanh nhạt", "Đen"],
    sizes: ["29", "30", "31", "32", "33", "34"],
    stock: 70,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Quần jean nữ ống rộng",
    description: "Quần jean nữ ống rộng dáng suông, phong cách Hàn Quốc.",
    price: 429000,
    discountPrice: 329000,
    category: "Quần jean",
    subcategory: "Quần jean nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh trung", "Trắng"],
    sizes: ["26", "27", "28", "29", "30"],
    stock: 60,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Quần jean nam rách gối",
    description: "Quần jean nam rách gối phong cách bụi bặm, cá tính.",
    price: 479000,
    discountPrice: 379000,
    category: "Quần jean",
    subcategory: "Quần jean nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1525134479668-1bee5c7c6845?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh đậm", "Đen"],
    sizes: ["29", "30", "31", "32", "33", "34"],
    stock: 50,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Quần jean nữ skinny cạp cao",
    description: "Quần jean nữ skinny cạp cao, tôn dáng, ôm vừa vặn.",
    price: 399000,
    discountPrice: 299000,
    category: "Quần jean",
    subcategory: "Quần jean nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?ixlib=rb-4.0.3"],
    colors: ["Xanh đậm", "Xanh nhạt", "Đen"],
    sizes: ["26", "27", "28", "29", "30"],
    stock: 65,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Quần jean nam straight",
    description: "Quần jean nam dáng straight-fit cổ điển, phù hợp mọi dáng người.",
    price: 469000,
    discountPrice: 369000,
    category: "Quần jean",
    subcategory: "Quần jean nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3"],
    colors: ["Xanh đậm", "Xanh nhạt", "Đen"],
    sizes: ["29", "30", "31", "32", "33", "34"],
    stock: 70,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Quần jean nữ boyfriend",
    description: "Quần jean nữ dáng boyfriend rộng rãi, thoải mái, phong cách cá tính.",
    price: 439000,
    discountPrice: 339000,
    category: "Quần jean",
    subcategory: "Quần jean nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1565084888279-aca607ecce0c?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh trung"],
    sizes: ["26", "27", "28", "29", "30"],
    stock: 55,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Quần jean nam slim",
    description: "Quần jean nam slim fit, ôm dáng vừa vặn, tôn dáng người mặc.",
    price: 449000,
    discountPrice: 349000,
    category: "Quần jean",
    subcategory: "Quần jean nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1604176424472-57a77ef07d8b?ixlib=rb-4.0.3"],
    colors: ["Xanh đậm", "Xanh nhạt", "Đen"],
    sizes: ["29", "30", "31", "32", "33", "34"],
    stock: 65,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Quần jean nữ ống loe",
    description: "Quần jean nữ ống loe cạp cao, phong cách retro, thanh lịch.",
    price: 469000,
    discountPrice: 369000,
    category: "Quần jean",
    subcategory: "Quần jean nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1582552938357-32b906df40cb?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh đậm", "Trắng"],
    sizes: ["26", "27", "28", "29", "30"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Quần jean nam loose",
    description: "Quần jean nam dáng loose rộng rãi, phong cách đường phố hiện đại.",
    price: 489000,
    discountPrice: 389000,
    category: "Quần jean",
    subcategory: "Quần jean nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1604176424472-57a77ef07d8b?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh đậm", "Đen"],
    sizes: ["29", "30", "31", "32", "33", "34"],
    stock: 45,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Quần jean nữ rách gối",
    description: "Quần jean nữ rách gối, phong cách cá tính, năng động.",
    price: 429000,
    discountPrice: 329000,
    category: "Quần jean",
    subcategory: "Quần jean nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1604176424472-57a77ef07d8b?ixlib=rb-4.0.3"],
    colors: ["Xanh nhạt", "Xanh đậm"],
    sizes: ["26", "27", "28", "29", "30"],
    stock: 60,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },

  // Váy đầm (10 sản phẩm)
  {
    name: "Đầm suông nữ công sở",
    description: "Đầm suông nữ thanh lịch, kiểu dáng đơn giản, phù hợp môi trường công sở.",
    price: 499000,
    discountPrice: 399000,
    category: "Váy đầm",
    subcategory: "Đầm công sở",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1596783074918-c84cb06531ca?ixlib=rb-4.0.3"],
    colors: ["Đen", "Xanh navy", "Đỏ đô"],
    sizes: ["S", "M", "L", "XL"],
    stock: 60,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Váy hoa nữ mùa hè",
    description: "Váy hoa nữ thiết kế nhẹ nhàng, thoáng mát, phù hợp mùa hè.",
    price: 429000,
    discountPrice: 329000,
    category: "Váy đầm",
    subcategory: "Váy hoa",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?ixlib=rb-4.0.3"],
    colors: ["Họa tiết hoa"],
    sizes: ["S", "M", "L"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Đầm maxi dự tiệc",
    description: "Đầm maxi dài sang trọng, phù hợp đi tiệc, đi chơi.",
    price: 599000,
    discountPrice: 499000,
    category: "Váy đầm",
    subcategory: "Đầm dự tiệc",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?ixlib=rb-4.0.3"],
    colors: ["Đen", "Đỏ", "Xanh navy"],
    sizes: ["S", "M", "L", "XL"],
    stock: 40,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Váy xòe midi",
    description: "Váy xòe midi thanh lịch, nữ tính, phù hợp nhiều dịp khác nhau.",
    price: 459000,
    discountPrice: 359000,
    category: "Váy đầm",
    subcategory: "Váy xòe",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1622122201284-98152dcd4cb8?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Đen", "Hồng phấn"],
    sizes: ["S", "M", "L"],
    stock: 55,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Đầm ôm body",
    description: "Đầm ôm body tôn dáng, thiết kế tinh tế, sang trọng.",
    price: 529000,
    discountPrice: 429000,
    category: "Váy đầm",
    subcategory: "Đầm ôm",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1551803091-e20673f15770?ixlib=rb-4.0.3"],
    colors: ["Đen", "Đỏ đô", "Xanh navy"],
    sizes: ["S", "M", "L"],
    stock: 45,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Váy liền thân chữ A",
    description: "Váy liền thân dáng chữ A, kiểu dáng thanh lịch, trẻ trung.",
    price: 439000,
    discountPrice: 339000,
    category: "Váy đầm",
    subcategory: "Váy chữ A",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1618244972963-dbad64b98d7d?ixlib=rb-4.0.3"],
    colors: ["Đen", "Kẻ caro", "Hồng"],
    sizes: ["S", "M", "L", "XL"],
    stock: 50,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Đầm voan nhẹ nhàng",
    description: "Đầm voan nhẹ nhàng, kiểu dáng bay bổng, nữ tính.",
    price: 489000,
    discountPrice: 389000,
    category: "Váy đầm",
    subcategory: "Đầm voan",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Hồng nhạt", "Xanh mint"],
    sizes: ["S", "M", "L"],
    stock: 40,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Váy tweed công sở",
    description: "Váy tweed phong cách Hàn Quốc, thanh lịch, sang trọng.",
    price: 559000,
    discountPrice: 459000,
    category: "Váy đầm",
    subcategory: "Váy công sở",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Đen", "Hồng"],
    sizes: ["S", "M", "L", "XL"],
    stock: 35,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 15
  },
  {
    name: "Đầm ren dự tiệc",
    description: "Đầm ren sang trọng, tinh tế, phù hợp đi tiệc, sự kiện.",
    price: 599000,
    discountPrice: 499000,
    category: "Váy đầm",
    subcategory: "Đầm dự tiệc",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?ixlib=rb-4.0.3"],
    colors: ["Đen", "Đỏ đô", "Trắng"],
    sizes: ["S", "M", "L"],
    stock: 30,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 15
  },
  {
    name: "Váy kẻ sọc dáng dài",
    description: "Váy kẻ sọc dáng dài, phong cách trẻ trung, năng động.",
    price: 469000,
    discountPrice: 369000,
    category: "Váy đầm",
    subcategory: "Váy dáng dài",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1496217590455-aa63a8350eea?ixlib=rb-4.0.3"],
    colors: ["Kẻ đen trắng", "Kẻ xanh trắng"],
    sizes: ["S", "M", "L"],
    stock: 45,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },

  // Giày (10 sản phẩm)
  {
    name: "Giày thể thao nam",
    description: "Giày thể thao nam phong cách năng động, đế mềm êm chân.",
    price: 699000,
    discountPrice: 549000,
    category: "Giày",
    subcategory: "Giày thể thao nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Đen", "Xám"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 60,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Giày thể thao nữ",
    description: "Giày thể thao nữ nhẹ, êm, thoáng khí, phù hợp đi chơi, tập thể dục.",
    price: 649000,
    discountPrice: 499000,
    category: "Giày",
    subcategory: "Giày thể thao nữ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Hồng", "Xanh mint"],
    sizes: ["35", "36", "37", "38", "39"],
    stock: 55,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Giày da nam công sở",
    description: "Giày da nam thiết kế thanh lịch, sang trọng, phù hợp môi trường công sở.",
    price: 899000,
    discountPrice: 749000,
    category: "Giày",
    subcategory: "Giày da nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1617689563472-c694d5f6755b?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 40,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Giày cao gót nữ",
    description: "Giày cao gót nữ thiết kế tinh tế, tôn dáng người mặc.",
    price: 799000,
    discountPrice: 649000,
    category: "Giày",
    subcategory: "Giày cao gót",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1611038776347-3b9b1e5121c2?ixlib=rb-4.0.3"],
    colors: ["Đen", "Kem", "Đỏ"],
    sizes: ["35", "36", "37", "38", "39"],
    stock: 45,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 15
  },
  {
    name: "Giày lười nam",
    description: "Giày lười nam thiết kế đơn giản, tiện lợi, thoải mái.",
    price: 599000,
    discountPrice: 499000,
    category: "Giày",
    subcategory: "Giày lười nam",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu", "Xanh navy"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 50,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Giày sandal nữ",
    description: "Giày sandal nữ thiết kế thanh lịch, thoáng mát, phù hợp mùa hè.",
    price: 499000,
    discountPrice: 399000,
    category: "Giày",
    subcategory: "Giày sandal",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1622428043967-ce0981664288?ixlib=rb-4.0.3"],
    colors: ["Đen", "Kem", "Nâu"],
    sizes: ["35", "36", "37", "38", "39"],
    stock: 60,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Giày boot nam",
    description: "Giày boot nam phong cách cá tính, chất liệu da cao cấp.",
    price: 999000,
    discountPrice: 849000,
    category: "Giày",
    subcategory: "Giày boot",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1638247025967-b4e38f787b76?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 35,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Giày sneaker nữ",
    description: "Giày sneaker nữ phong cách Hàn Quốc, trẻ trung, năng động.",
    price: 699000,
    discountPrice: 559000,
    category: "Giày",
    subcategory: "Giày sneaker",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?ixlib=rb-4.0.3"],
    colors: ["Trắng", "Đen", "Hồng"],
    sizes: ["35", "36", "37", "38", "39"],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Giày mọi nam",
    description: "Giày mọi nam thiết kế đơn giản, lịch sự, phù hợp đi làm, đi chơi.",
    price: 749000,
    discountPrice: 649000,
    category: "Giày",
    subcategory: "Giày mọi",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1614253375744-7959d5df1c96?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: ["39", "40", "41", "42", "43"],
    stock: 40,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Giày bít mũi nữ",
    description: "Giày bít mũi nữ kiểu dáng thanh lịch, sang trọng, phù hợp công sở.",
    price: 599000,
    discountPrice: 499000,
    category: "Giày",
    subcategory: "Giày bít mũi",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1591022360173-104ea5ed6036?ixlib=rb-4.0.3"],
    colors: ["Đen", "Kem", "Nude"],
    sizes: ["35", "36", "37", "38", "39"],
    stock: 45,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 15
  },

  // Phụ kiện (10 sản phẩm)
  {
    name: "Túi xách nữ thời trang",
    description: "Túi xách nữ thiết kế thời trang, sang trọng, chất liệu da cao cấp.",
    price: 799000,
    discountPrice: 649000,
    category: "Phụ kiện",
    subcategory: "Túi xách",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1597843797341-728c4b43c0b0?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu", "Đỏ đô"],
    sizes: [],
    stock: 30,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Ví nam da thật",
    description: "Ví nam chất liệu da thật cao cấp, thiết kế tinh tế, sang trọng.",
    price: 559000,
    discountPrice: 459000,
    category: "Phụ kiện",
    subcategory: "Ví",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1606751296969-d7b0585d0c07?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: [],
    stock: 40,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Thắt lưng nam da bò",
    description: "Thắt lưng nam chất liệu da bò thật, thiết kế đơn giản, thanh lịch.",
    price: 499000,
    discountPrice: 399000,
    category: "Phụ kiện",
    subcategory: "Thắt lưng",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1624222247888-511d6f6d8bfa?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: [],
    stock: 45,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Kính mát nữ",
    description: "Kính mát nữ phong cách hiện đại, thời trang, chống tia UV.",
    price: 399000,
    discountPrice: 299000,
    category: "Phụ kiện",
    subcategory: "Kính mát",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu", "Hồng"],
    sizes: [],
    stock: 50,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Đồng hồ nam dây da",
    description: "Đồng hồ nam dây da thiết kế thanh lịch, sang trọng, phù hợp đi làm, đi chơi.",
    price: 1299000,
    discountPrice: 999000,
    category: "Phụ kiện",
    subcategory: "Đồng hồ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1533139502658-0198f920d8e8?ixlib=rb-4.0.3"],
    colors: ["Đen", "Nâu"],
    sizes: [],
    stock: 30,
    isFeatured: true,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Balo laptop thời trang",
    description: "Balo laptop thiết kế thời trang, tiện lợi, chống sốc tốt.",
    price: 699000,
    discountPrice: 549000,
    category: "Phụ kiện",
    subcategory: "Balo",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-4.0.3"],
    colors: ["Đen", "Xanh navy", "Xám"],
    sizes: [],
    stock: 40,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Nón bucket unisex",
    description: "Nón bucket unisex phong cách Hàn Quốc, thời trang, dễ phối đồ.",
    price: 249000,
    discountPrice: 189000,
    category: "Phụ kiện",
    subcategory: "Nón",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1556306535-0f09a537f0a3?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Beige"],
    sizes: [],
    stock: 60,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 25
  },
  {
    name: "Vòng tay bạc nữ",
    description: "Vòng tay bạc nữ thiết kế tinh tế, sang trọng, phù hợp nhiều phong cách.",
    price: 359000,
    discountPrice: 289000,
    category: "Phụ kiện",
    subcategory: "Trang sức",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1611652022419-a9419f74628c?ixlib=rb-4.0.3"],
    colors: ["Bạc"],
    sizes: [],
    stock: 35,
    isFeatured: false,
    isFlashSale: false,
    flashSaleDiscount: null
  },
  {
    name: "Khăn choàng cổ",
    description: "Khăn choàng cổ chất liệu mềm mại, ấm áp, phong cách thời trang.",
    price: 299000,
    discountPrice: 229000,
    category: "Phụ kiện",
    subcategory: "Khăn choàng",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1570950913925-1753ee73bc2c?ixlib=rb-4.0.3"],
    colors: ["Kẻ caro", "Đỏ", "Đen", "Xám"],
    sizes: [],
    stock: 45,
    isFeatured: true,
    isFlashSale: true,
    flashSaleDiscount: 20
  },
  {
    name: "Mũ lưỡi trai nam",
    description: "Mũ lưỡi trai nam phong cách thể thao, năng động, trẻ trung.",
    price: 199000,
    discountPrice: 149000,
    category: "Phụ kiện",
    subcategory: "Mũ",
    sellerId: 1,
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?ixlib=rb-4.0.3"],
    colors: ["Đen", "Trắng", "Xanh navy"],
    sizes: [],
    stock: 55,
    isFeatured: false,
    isFlashSale: true,
    flashSaleDiscount: 25
  }
];

